name: Build JAR

on:

  push:

    branches: [ "main" ]

  pull_request:

    branches: [ "main" ]

  release:

    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 17

      uses: actions/setup-java@v3

      with:

        java-version: '17'

        distribution: 'temurin'

        cache: maven

    - name: Build

      run: mvn package

    - name: Upload a Build Artifact

      uses: actions/upload-artifact@v3.1.2

      with:

    # Artifact name

       name: Jar

    # A file, directory or wildcard pattern that describes what to upload

       path: ./target/DrawPerfectCycle-1.0-SNAPSHOT-jar-with-dependencies.jar

       if-no-files-found: error

    
